### ISSUE TITLE
Drop bash dependency

### ISSUE THREAD

**Issue by AMDmi3** [nemequ/configure-cmake#5] opened 2016-01-26 14:08 UTC
Drop bash requirement. Real configure scripts do not require extra dependencies, and bash is not available out of box in many environments including *BSD systems. This should be fairly easy, the only real bash feature used is CMAKE_ARGS array, which could be replaces with three plain variables (which will make the code cleaner as well).

**Comment by nemequ** [comment] 2016-01-26 16:57
I originally tried to get it working with plain variables, and getting the quoting right was a nightmare.  I'm happy to accept patches, but it's probably best not to wait for me to write the code.

Closing as a duplicate of #1

**Closed as completed by nemequ** 2016-01-26 16:57 UTC

**Comment by AMDmi3** [comment] 2016-01-26 17:57
> I'm happy to accept patches, but it's probably best not to wait for me to write the code.

Sorry, since I'm not going to use this I'm not really motivated to write code. But I can test it for you on FreeBSD :)

**Comment by nemequ** [comment] 2016-01-26 19:25
Heh, that's pretty much how I feel about it, too.  Everywhere I'm interested in using it has bash, so I'm not really motivated to work around deficiencies of other shells, and trying to resolve quoting issues in shell scripts isn't exactly my idea of a good time.
